apiVersion: v1
kind: Service
metadata:
  name: drones-redis-service
  labels:
    app: drones-redis
spec:
  type: ClusterIP
  selector:
    app: drones-redis
  ports:
    - port: 6379
      targetPort: 6379
