apiVersion: apps/v1
kind: Deployment
metadata:
  name: drones-postgres-deployment
  labels:
    app: drones-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drones-postgres
  template:
    metadata:
      labels:
        app: drones-postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:15.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "drones_user"
            - name: POSTGRES_PASSWORD
              value: "drones_password"
            - name: POSTGRES_DB
              value: "drones_db"
          ports:
            - containerPort: 5432
