apiVersion: apps/v1
kind: Deployment
metadata:
  name: drones-frontend-deployment
  labels:
    app: drones-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: drones-frontend
  template:
    metadata:
      labels:
        app: drones-frontend
    spec:
      containers:
        - name: drones-frontend
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: 5173
