apiVersion: apps/v1
kind: Deployment
metadata:
  name: drones-frontend-deployment
  labels:
    app: drones-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drones-frontend
  template:
    metadata:
      labels:
        app: drones-frontend
    spec:
      containers:
        - name: drones-frontend
          image: "ghcr.io/max-vassilev/drones-frontend:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
