apiVersion: v1
kind: Service
metadata:
  name: drones-frontend-service
  labels:
    app: drones-frontend
spec:
  type: ClusterIP
  selector:
    app: drones-frontend
  ports:
    - port: 5173
      targetPort: 5173
