replicaCount: 1
image:
  repository: postgres
  tag: "15.3"
  pullPolicy: IfNotPresent
postgres:
  username: drones_user
  password: drones_password
  database: drones_db
service:
  type: ClusterIP
  port: 5432
