apiVersion: v1
kind: Service
metadata:
  name: drones-backend-service
  labels:
    app: drones-backend
spec:
  type: ClusterIP
  selector:
    app: drones-backend
  ports:
    - port: 8080
      targetPort: 8080
